<?php

namespace Proxies\__CG__\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \UserBundle\Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'firstname', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'lastname', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'address_line_1', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'address_line_2', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'profile', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'bill', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'phone', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'city');
        }

        return array('__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'firstname', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'lastname', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'address_line_1', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'address_line_2', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'profile', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'bill', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'phone', '' . "\0" . 'UserBundle\\Entity\\Customer' . "\0" . 'city');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', array($lastname));

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', array());

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressLine1($addressLine1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressLine1', array($addressLine1));

        return parent::setAddressLine1($addressLine1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressLine1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressLine1', array());

        return parent::getAddressLine1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressLine2($addressLine2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressLine2', array($addressLine2));

        return parent::setAddressLine2($addressLine2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressLine2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressLine2', array());

        return parent::getAddressLine2();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile(\UserBundle\Entity\Profile $profile = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', array($profile));

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', array());

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function addBill(\BillingBundle\Entity\Bill $bill)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBill', array($bill));

        return parent::addBill($bill);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBill(\BillingBundle\Entity\Bill $bill)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBill', array($bill));

        return parent::removeBill($bill);
    }

    /**
     * {@inheritDoc}
     */
    public function getBill()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBill', array());

        return parent::getBill();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone(\UserBundle\Entity\Phone $phone = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(\UserBundle\Entity\City $city = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

}
